//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventInventory
    {
        public int eventInventoryID { get; set; }
        public int eventID { get; set; }
        public int inventoryID { get; set; }
        public Nullable<int> memberID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual Member Member { get; set; }
    }
}
