//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oDataService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EventsView
    {
        public int eventID { get; set; }
        public string location { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string eventName { get; set; }
        [Key]
        public int inventoryID { get; set; }
        public int itemID { get; set; }
        public System.DateTime dateAdded { get; set; }
        public decimal condition { get; set; }
        public Nullable<decimal> price { get; set; }
        public string purchasedAt { get; set; }
        public string itemName { get; set; }
        public string itemDescription { get; set; }
        public string type { get; set; }
        public string memberFName { get; set; }
        public string memberLName { get; set; }
        public string memberAddress { get; set; }
        public string memberEmail { get; set; }
        public Nullable<decimal> memberPhone { get; set; }
        public string hostFName { get; set; }
        public string hostLName { get; set; }
        public string hostEmail { get; set; }
        public Nullable<decimal> hostPhone { get; set; }
    }
}
