//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oDataService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryManagerDatabaseEntities : DbContext
    {
        public InventoryManagerDatabaseEntities()
            : base("name=InventoryManagerDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EventInventory> EventInventories { get; set; }
        public virtual DbSet<EventMember> EventMembers { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<EventsView> EventsViews { get; set; }
        public virtual DbSet<InventoryUsage> InventoryUsages { get; set; }
        public virtual DbSet<PurchasedAt> PurchasedAts { get; set; }
        public virtual DbSet<TypesView> TypesViews { get; set; }
    }
}
